# 데이터 읽어오기

In [3]:
import pandas as pd
import numpy as np
movies = pd.read_csv("./dataset/tmdb_5000_movies.csv")         # tmdb_5000_movies.csv dataframe으로 읽어오기
movies = movies[["id","genres","vote_average","vote_count","popularity","original_title", "keywords","overview"]]
movies.drop(["genres","vote_average","vote_count","popularity", "keywords","overview"],axis=1,inplace=True)

print(movies.shape)
movies.head()

(4803, 2)


id                            original_title
0   19995                                    Avatar
1     285  Pirates of the Caribbean: At World's End
2  206647                                   Spectre
3   49026                     The Dark Knight Rises
4   49529                               John Carter

In [4]:
# 컬럼명 변경
movies.columns = ['tmdbId', 'original_title']
movies.head()

tmdbId                            original_title
0   19995                                    Avatar
1     285  Pirates of the Caribbean: At World's End
2  206647                                   Spectre
3   49026                     The Dark Knight Rises
4   49529                               John Carter

In [5]:
# links.csv dataframe으로 읽어오기
links = pd.read_csv("./dataset/links_small.csv")
links = links[["movieId","imdbId","tmdbId"]]
links.drop(['imdbId'],axis=1,inplace=True)

print(links.shape)
links.head()

(9125, 2)


movieId   tmdbId
0        1    862.0
1        2   8844.0
2        3  15602.0
3        4  31357.0
4        5  11862.0

In [6]:
# ratings.csv dataframe으로 읽어오기
ratings = pd.read_csv("./dataset/ratings_small.csv")   
ratings = ratings[["userId","movieId","rating","timestamp"]]
ratings.drop(["timestamp"],axis=1,inplace=True)

print(ratings.shape)
ratings.head()

(100004, 3)


userId  movieId  rating
0       1       31     2.5
1       1     1029     3.0
2       1     1061     3.0
3       1     1129     2.0
4       1     1172     4.0

## 결측값 확인


In [7]:
# null 값 개수 확인
movies.isnull().sum()

tmdbId            0
original_title    0
dtype: int64

In [8]:
# null 값 개수 확인
links.isnull().sum()

movieId     0
tmdbId     13
dtype: int64

In [9]:
# 결측값 있는 로우 제거
links = links.dropna(axis=0)

# 타입변환
links["tmdbId"] = links["tmdbId"].astype("int")

links.head()

movieId  tmdbId
0        1     862
1        2    8844
2        3   15602
3        4   31357
4        5   11862

In [10]:
# null 값 개수 확인
ratings.isnull().sum()

userId     0
movieId    0
rating     0
dtype: int64

## 데이터 프레임끼리 inner join

In [11]:
join_movie = pd.merge(ratings, links, left_on='movieId', right_on='movieId', how='inner')
print(join_movie)

       userId  movieId  rating  tmdbId
0           1       31     2.5    9909
1           7       31     3.0    9909
2          31       31     4.0    9909
3          32       31     4.0    9909
4          36       31     3.0    9909
...       ...      ...     ...     ...
99928     664    64997     2.5   34812
99929     664    72380     3.5   22825
99930     665      129     3.0  110972
99931     665     4736     1.0   26602
99932     668     6425     1.0   36807

[99933 rows x 4 columns]


In [12]:
join_movie = pd.merge(join_movie, movies, left_on='tmdbId', right_on='tmdbId', how='inner')
print(join_movie)

       userId  movieId  rating  tmdbId  original_title
0           1     1061     3.0     819        Sleepers
1          19     1061     3.0     819        Sleepers
2          23     1061     3.5     819        Sleepers
3          30     1061     3.0     819        Sleepers
4          70     1061     5.0     819        Sleepers
...       ...      ...     ...     ...             ...
66942     663   134528     3.5  222936           Aloha
66943     663   137595     3.0  264999  Magic Mike XXL
66944     664    60832     3.0   12192       Pathology
66945     664    72380     3.5   22825         The Box
66946     665     4736     1.0   26602    Summer Catch

[66947 rows x 5 columns]


In [13]:
join_movie["original_title"].value_counts()

Forrest Gump                341
Pulp Fiction                324
The Shawshank Redemption    311
The Silence of the Lambs    304
Star Wars                   291
                           ... 
Isn't She Great               1
Monsters                      1
FearDotCom                    1
Cheap Thrills                 1
Mr. Peabody & Sherman         1
Name: original_title, Length: 3393, dtype: int64

In [14]:
# # movies에 있던 모든 영화가 join이 잘 됐는지 확인 -> 여긴 발표할 때는 빼도 될 듯..
# after = join_movie["tmdbId"].unique()
# print(len(after))
# print(movies.shape)

## latent 알고리즘

### 피벗테이블 생성

In [15]:
user_movie_rating = join_movie.pivot_table('rating', index = 'userId', columns='tmdbId').fillna(0)
# user_movie_rating = join_movie.pivot_table('rating', index = 'userId', columns='tmdbId')
print(user_movie_rating.shape)
user_movie_rating.head()

(671, 3394)


tmdbId  5       11      12      13      ...  333371  334074  342521  347969
userId                                  ...                                
1          NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
2          NaN     NaN     NaN     3.0  ...     NaN     NaN     NaN     NaN
3          NaN     NaN     3.0     5.0  ...     NaN     NaN     NaN     NaN
4          NaN     5.0     NaN     5.0  ...     NaN     NaN     NaN     NaN
5          NaN     NaN     4.0     4.0  ...     NaN     NaN     NaN     NaN

[5 rows x 3394 columns]

## 특이값 분해 (Singular Value Decomposion, SVD)
행렬을 여러 행렬의 곱으로 분해해준다. </br>
[참고 사이트](https://ratsgo.github.io/from%20frequency%20to%20semantics/2017/04/06/pcasvdlsa/)

scipy의 Truncated SVD 이용 </br>

반환값: U 행렬, Sigma 행렬, V 전치 행렬(Vt)



In [16]:
from scipy.sparse.linalg import svds
import numpy as np

# scipy에서 제공해주는 svd.  
# U 행렬, sigma 행렬, V 전치 행렬을 반환.

U, sigma, Vt = svds(user_movie_rating, k = 100)


print(U.shape)
print(sigma.shape)
print(Vt.shape)

/usr/local/lib/python3.6/dist-packages/scipy/sparse/linalg/eigen/arpack/arpack.py:1883: RuntimeWarning: invalid value encountered in greater
  above_cutoff = (eigvals > cutoff)


(671, 100)
(100,)
(100, 3394)



현재 이 Sigma 행렬은 0이 아닌 값만 1차원 행렬로 표현된 상태->0이 포함된 대칭행렬로 변환할 때는 numpy의 diag를 이용

In [17]:
sigma = np.diag(sigma)

tmp = pd.DataFrame(data=sigma, index=None, columns=None, dtype=None, copy=False)
print(tmp.shape)
tmp.head()

(100, 100)


0    1    2    3    4    5    6   ...   93   94   95   96   97   98   99
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 100 columns]

## 원래 행렬로 복구

U, Sigma, Vt의 내적을 수행

In [18]:
# U, Sigma, Vt의 내적을 수행하면, 다시 원본 행렬로 복원이 된다. 

svd_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) 


In [19]:
df_svd_preds = pd.DataFrame(svd_user_predicted_ratings, columns = user_movie_rating.columns)
print(df_svd_preds.shape)
df_svd_preds.head()

(671, 3394)


tmdbId  5       11      12      13      ...  333371  334074  342521  347969
0          0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
1          0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
2          0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
3          0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
4          0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0

[5 rows x 3394 columns]

In [20]:
from sklearn.metrics import mean_squared_error


# 실제 R 행렬과 예측 행렬의 오차를 구하는 함수
def calculate_rmse(R, P, Q, non_zeros):
    error = 0

    full_pred_matrix = np.dot(P, Q.T)

    # 여기서 non_zeros는 아래 함수에서 확인할 수 있다.
    x_non_zero_ind = [non_zeros[0] for non_zeros in non_zeros]
    y_non_zero_ind = [non_zeros[1] for non_zeros in non_zeros]

    # 원 행렬 R에서 0이 아닌 값들만 추출한다.
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]

    # 예측 행렬에서 원 행렬 R에서 0이 아닌 위치의 값들만 추출하여 저장한다.
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]

    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)

    return rmse


def matrix_factorization(R, K, steps=100, learning_rate=0.01, r_lambda=0.01):
    num_users, num_items = R.shape

    np.random.seed(1)
    P = np.random.normal(scale=1.0/K, size=(num_users, K))
    Q = np.random.normal(scale=1.0/K, size=(num_items, K))

    # R>0인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장한다.
    non_zeros = [ (i, j, R[i, j]) for i in range(num_users)
                  for j in range(num_items) if R[i, j] > 0 ]

    # SGD 기법으로 P, Q 매트릭스를 업데이트 함
    for step in range(steps):
        for i, j, r in non_zeros:
            # 잔차 구함
            eij = r - np.dot(P[i, :], Q[j, :].T)

            # Regulation을 반영한 SGD 업데이터 적용
            P[i, :] = P[i, :] + learning_rate*(eij * Q[j, :] - r_lambda*P[i, :])
            Q[j, :] = Q[j, :] + learning_rate*(eij * P[i, :] - r_lambda*Q[j, :])

        rmse = calculate_rmse(R, P, Q, non_zeros)
        if step % 10 == 0:
            print("iter step: {0}, rmse: {1:4f}".format(step, rmse))

    return P, Q

P, Q = matrix_factorization(user_movie_rating.values, K=3)
pred_matrix = np.dot(P, Q.T)
print(pred_matrix)

iter step: 0, rmse: 2.615706
iter step: 10, rmse: 0.856848
iter step: 20, rmse: 0.813864
iter step: 30, rmse: 0.793731
iter step: 40, rmse: 0.780472
iter step: 50, rmse: 0.770871
iter step: 60, rmse: 0.764027
iter step: 70, rmse: 0.759228
iter step: 80, rmse: 0.755759
iter step: 90, rmse: 0.753154
iter step: 100, rmse: 0.751162
iter step: 110, rmse: 0.749618
iter step: 120, rmse: 0.748390
iter step: 130, rmse: 0.747387
iter step: 140, rmse: 0.746549
iter step: 150, rmse: 0.745839
iter step: 160, rmse: 0.745231
iter step: 170, rmse: 0.744706
iter step: 180, rmse: 0.744249
iter step: 190, rmse: 0.743848
[[1.76897411 3.1544787  2.15897124 ... 1.32105094 0.88107398 1.21498791]
 [3.60024157 3.92663784 4.03945049 ... 2.8695976  0.37581765 2.19400046]
 [3.41100741 4.17208103 4.09017623 ... 2.93801356 0.34225858 2.20535621]
 ...
 [3.12617473 4.29722409 3.90657301 ... 2.77318986 0.45949023 2.10885494]
 [2.82209349 4.28611049 3.85550551 ... 2.8175759  0.27704741 2.05306369]
 [3.62765276 4.222228

In [21]:
df_svd_preds = pd.DataFrame(pred_matrix, columns = user_movie_rating.columns)
print(df_svd_preds.shape)
df_svd_preds.head()

(671, 3394)


tmdbId    5         11        12      ...    334074    342521    347969
0       1.768974  3.154479  2.158971  ...  1.321051  0.881074  1.214988
1       3.600242  3.926638  4.039450  ...  2.869598  0.375818  2.194000
2       3.411007  4.172081  4.090176  ...  2.938014  0.342259  2.205356
3       4.016853  5.032875  4.849932  ...  3.471757  0.449008  2.616676
4       4.309973  4.308067  4.625779  ...  3.268352  0.436576  2.523558

[5 rows x 3394 columns]